spring:
  datasource:
    url: jdbc:sqlserver://bharserver.database.windows.net:1433;database=bhardb;user=bharserver@bharserver;password=pass@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: bharserver
    password: pass@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


